FROM php:7.2-stretch

MAINTAINER "Egor Burykin <egor.burykin@avesystems.ru>"

RUN apt-get update && apt-get install -y librabbitmq-dev libssh-dev git wget \
    && docker-php-ext-install opcache bcmath sockets \
    && pecl install amqp \
&& docker-php-ext-enable amqp

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

WORKDIR /app

COPY . .

RUN composer install --no-dev --optimize-autoloader

CMD [ "php", "./executor.php"]
