version: "3"
services: 
  scheduler:
    image: egorburykin/scheduler
    depends_on:
      - rabbitmq
    volumes:
        - app:/var/www/html
  executor: 
    depends_on: 
      - rabbitmq
    image: egorburykin/executor
  nginx: 
    depends_on: 
      - scheduler
    image: "nginx:alpine"
    ports: 
      - "8001:80"
    volumes: 
      - "./nginx/vhost.conf:/etc/nginx/conf.d/default.conf"
      - app:/var/www/html
  rabbitmq: 
    image: "rabbitmq:alpine"
    ports: 
      - "5672:5672"
volumes:
   app:
